server:
  port: 8081
spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/product_service
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
user:
  password: dev_Password
